### ISSUE TITLE
Question about section 3.2.2

### ISSUE THREAD

**Issue by Borororo** [ari9dam/OBQA#4]
Thanks for sharing nice work!
I have one question about section 3.2.2 in your paper. 
Does gold fact for openbookQA  come from official "additional" folder?  Is it allowable to train a model based on these data?  Since the official website writes "This data is only meant for analysis and should not be used by the model" [https://leaderboard.allenai.org/open_book_qa/submissions/get-started](url)

**Comment by pratyay-banerjee** [comment]
So its is not allowed to be used directly in the OBQA task. As the gold has direct overlap with the correct answer. We have used the gold facts for training our knowledge hunting module, for a given and openbook knowledge, what kind of gold knowledge to look for, or it should rank higher.

**Comment by Borororo** [comment]
Thanks for your reply,  it made sense.  That's why you sample difference facts instead of directly using golden facts.
